### ISSUE TITLE
request

### ISSUE THREAD

**Issue by jjjan** [AlphaDelta/Secure-Desktop#2]
Hello,

great tool .may i know where is SecureDesktop.exe file?

is your program work like sandbox if yes, could you make log of executable file in text file?

**Comment by AlphaDelta** [comment]
If you downloaded it from the releases page it should be in the archive file along with Cleanup.exe, Gma.UserActivityMonitor.dll, and SecureDesktop-GUI.exe
![e4iy67x](https://cloud.githubusercontent.com/assets/2088238/9423506/9acbc17e-491a-11e5-9628-3937d7ae833a.png)

If however you're compiling it, it should be in either `SecureDesktop\bin\Release\` or `SecureDesktop\bin\Debug\` depending on what your solution configuration is set to.

**Comment by lorloffc** [comment]
Hello @AlphaDelta .
Can you upload the Cleanup.exe, Gma.UserActivityMonitor.dll, SecureDesktop-GUI.exe, and SecureDesktop.exe ? Please. Coz, I don't know where the releases page.
I just want to avoid mouse and keyboard hooks. :(
Many thanks.

**Comment by AlphaDelta** [comment]
@lorloffc It's right here: https://github.com/AlphaDelta/Secure-Desktop/releases
